//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidTownHunterLocal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BidTown540Entities : DbContext
    {
        public BidTown540Entities()
            : base("name=BidTown540Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bird> Birds { get; set; }
        public virtual DbSet<Bug> Bugs { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Is_Watching> Is_Watching { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Mammal> Mammals { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Reptile> Reptiles { get; set; }
        public virtual DbSet<Seller_Applications> Seller_Applications { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
