//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidTownHunterLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Birds = new HashSet<Bird>();
            this.Bugs = new HashSet<Bug>();
            this.Is_Watching = new HashSet<Is_Watching>();
            this.Mammals = new HashSet<Mammal>();
            this.Reptiles = new HashSet<Reptile>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public int ClassID { get; set; }
        public string Name { get; set; }
        public string Image_Url { get; set; }
        public string Status { get; set; }
        public int Start_Bid { get; set; }
        public Nullable<int> Current_Bid { get; set; }
        public Nullable<int> Bid_Count { get; set; }
        public int Start_Date { get; set; }
        public int End_Date { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public int Weight { get; set; }
        public int Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bird> Birds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bug> Bugs { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Is_Watching> Is_Watching { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mammal> Mammals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reptile> Reptiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
