//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidTownHunterLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reptile
    {
        public int ReptileID { get; set; }
        public int ClassID { get; set; }
        public int ItemID { get; set; }
        public bool Shell { get; set; }
        public bool Poisonous { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Item Item { get; set; }
    }
}
