//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidTownHunterLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public int UserID2 { get; set; }
        public int ItemID { get; set; }
        public string Comments { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
